
@authToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiTWVtYmVyIiwiQWRtaW4iXSwiZXhwIjoxNzI4MjMwODk5fQ.jsLHQbAxG6KhJZitTicIlZ2nqBvL2NAI0gLcn74_1PVZ1VXm-K8m5rrwHUnSz-uLIEY02UX6e37sVHBQW6G7Lg
### Get all countries
GET  {{baseUrl}}/api/countries

### Get country by Id use Apikey or Admin role
GET  {{baseUrl}}/api/countries/35
Authorization: Bearer {{authToken}}

### Create a new country
POST  {{baseUrl}}/api/countries
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "name": "Ser6bian25",
  "description": "Not bad as mad",
  "mainImageURL": "23",
  "secondaryImageURL": "2223",
  "continent": "467"
}

### Update the country
PUT  {{baseUrl}}/api/countries/35222
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "id":325,
  "name": "Italyyyius",
  "description": "Not bad as mad2",
  "mainImageURL": "23",
  "secondaryImageURL": "2223",
  "continent": "Australia"
}

### Delete the country
DELETE  {{baseUrl}}/api/countries/29
Content-Type: application/json
Authorization:Bearer {{authToken}}