
@authToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiTWVtYmVyIiwiQWRtaW4iXSwiZXhwIjoxNzI0NTcwNTY5fQ.kXw2GvDbDbeV0Q2Kq2WP8_rNcCoUW_8Yi8Uw1ZO71uINh86FB8dOoTzEg2se0_3k0DkOdsP-IeymOMKphrxRqw

### Get all countries
GET  {{baseUrl}}/api/countries
Authorization: Bearer {{authToken}}

### Get country by Id
GET  {{baseUrl}}/api/countries/12
Authorization: Bearer {{authToken}}

### Create a new country
POST  {{baseUrl}}/api/countries
x-api-key: ab813b98016e4cf181cb20b88f756f28
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "name": "polanduis",
  "description": "Not bad as mad",
  "mainImageURL": "23",
  "secondaryImageURL": "2223"
}

### Update the country
Put  {{baseUrl}}/api/countries/18
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "id":18,
  "name": "Italy3",
  "description": "Not bad as mad2",
  "mainImageURL": "23",
  "secondaryImageURL": "2223"
}

### Update the country
DELETE  {{baseUrl}}/api/countries/12
Content-Type: application/json
Authorization:Bearer {{authToken}}