
@authToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiTWVtYmVyIiwiQWRtaW4iXSwiZXhwIjoxNzI4MTM1MzI0fQ.WA5uUGSFDGuoJ1zCy5uDjGDNT8XkgTTx59i6Ea9v7ZCudCnmtvIgh2O3qJaJw7rGndNwGGubXgbqnEGmIvCmzg
### Get all countries
GET  {{baseUrl}}/api/countries

### Get country by Id use Apikey or Admin role
GET  {{baseUrl}}/api/countries/35
Authorization: Bearer {{authToken}}

### Create a new country
POST  {{baseUrl}}/api/countries
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "name": "iii2 love p2oland223",
  "description": "Not bad as mad",
  "mainImageURL": "23",
  "secondaryImageURL": "2223",
  "continent": "Europe"
}

### Update the country
PUT  {{baseUrl}}/api/countries/35
Content-Type: application/json
Authorization:Bearer {{authToken}}

{
  "id":35,
  "name": "Italyyyius",
  "description": "Not bad as mad2",
  "mainImageURL": "23",
  "secondaryImageURL": "2223",
  "continent": "Australia"
}

### Delete the country
DELETE  {{baseUrl}}/api/countries/29
Content-Type: application/json
Authorization:Bearer {{authToken}}